import base64
import os
from typing import Any, Dict

import requests
from dotenv import load_dotenv
from fastapi import FastAPI, Request, Response
from twilio.twiml.messaging_response import MessagingResponse

from gabriela.agent.core import WhatsAppAgent

# Load environment variables from .env file
load_dotenv()

app = FastAPI()

# Initialize WhatsApp agent
wa = WhatsAppAgent()


@app.post("/whatsapp")
async def whatsapp_reply(request: Request):
    form_data = await request.form()
    incoming_msg = form_data.get("Body", "").strip()  # Received message
    sender = form_data.get("From", "").strip()  # Sender's number
    media_url = form_data.get("MediaUrl0")  # Get the image URL if present
    resp = MessagingResponse()
    msg = resp.message()

    if incoming_msg or media_url:
        try:
            # Transform MediaUrl0 into a base64 encoded string
            base64_image = None
            if media_url:
                response = requests.get(media_url)
                if response.status_code == 200:
                    image_content = response.content
                    base64_image = base64.b64encode(image_content).decode("utf-8")

            # Call the handle_message method of WhatsAppAgent
            agent_response: Dict[str, Any] = wa.handle_message(
                {
                    "from": sender,
                    "text": incoming_msg,
                    "image_url": (
                        f"data:image/jpeg;base64,{base64_image}"
                        if base64_image
                        else None
                    ),
                }
            )
            response_content = agent_response["messages"][-1].content
            msg.body(response_content)  # Send the response generated by the agent
        except Exception as e:
            print(
                f"Error processing message: {e}"
            )  # Use print for logging in this example
            msg.body("Sorry, an error occurred while processing your message.")
    else:
        msg.body("I didn't receive any message or image. Can you please try again?")

    return Response(content=str(resp), media_type="application/xml")
