from flask import Flask, request
from twilio.twiml.messaging_response import MessagingResponse
from openai import OpenAI
from dotenv import load_dotenv
import os
from agent.core import WhatsAppAgent

# Load environment variables from .env file
load_dotenv()

app = Flask(__name__)

# Initialize WhatsApp agent
wa = WhatsAppAgent()

@app.route('/whatsapp', methods=['POST'])
def whatsapp_reply():
    incoming_msg = request.values.get('Body', '').strip()  # Received message
    sender = request.values.get('From', '').strip()  # Sender's number
    resp = MessagingResponse()
    msg = resp.message()

    if incoming_msg:
        # Call the custom agent to generate a response
        try:
            # Call the handle_message method of WhatsAppAgent
            agent_response = wa.handle_message({'from': sender, 'text': incoming_msg})['messages'][-1].content
            msg.body(agent_response)  # Send the response generated by the agent
        except Exception as e:
            msg.body(f"Sorry, an error occurred: {e}")
    else:
        msg.body("I don't understand your message. Can you please repeat it?")

    return str(resp)

if __name__ == '__main__':
    app.run(debug=True)